/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface RogCons {
  value: number
  values: Array<number>
  text: string
  boolean: boolean
  dice: number
}
export interface Output {
  cons: Array<RogCons>
  attrMap: Record<string, number>
}
export function parse(input: string, attrMap: Record<string, number>): Output | null
